apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-basic-server
  labels:
    app: theo777c270/simple_server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: theo777c270/simple_server
  template:
    metadata:
      labels:
        app: theo777c270/simple_server
    spec:
      containers:
      - name: py-basic-server
        image: theo777c270/simple_server
        ports:
        - containerPort: 8000
